image: maven:3.6.3-jdk-11
stages:
  - clean
  - compile
  - package

clean:
  stage: clean
  script:
    - "mvn clean"

compile:
  stage: compile
  script:
    - "mvn compile"

package:
  stage: package
  script:
    - "mvn package"
